root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/kzen-go ."
  entrypoint = ["./tmp/kzen-go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  exclude_file = []
  exclude_regex = [".*_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
